### ISSUE TITLE
Force closes when setting speed to 0 and scrolling

### ISSUE THREAD

**Issue by TomerRosenfeld** [jpardogo/ListBuddies#19]
The app force closes after setting the speed to 0 and scrolling up/down

**Comment by technohowl** [comment]
`05-06 21:33:11.228 16364-16364/? E/InputEventReceiver: Exception dispatching input event.
05-06 21:33:11.228 16364-16364/? E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
05-06 21:33:11.230 16364-16364/? E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPressed(boolean)' on a null object reference
                                                         at com.jpardogo.listbuddies.lib.views.ListBuddiesLayout.performClick(ListBuddiesLayout.java:396)
                                                         at com.jpardogo.listbuddies.lib.views.ListBuddiesLayout.actionUp(ListBuddiesLayout.java:375)
                                                         at com.jpardogo.listbuddies.lib.views.ListBuddiesLayout.onTouch(ListBuddiesLayout.java:299)
                                                         at android.view.View.dispatchTouchEvent(View.java:9331)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                         at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2425)
                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1743)
                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:2805)
                                                         at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.dispatchTouchEvent(ActionBarActivityDelegateICS.java:260)
                                                         at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2386)
                                                         at android.view.View.dispatchPointerEvent(View.java:9557)
                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4263)
                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4102)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3789)
                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3846)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5955)
                                                         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5929)
                                                         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5890)
                                                         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6058)
                                                         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                                         at android.os.MessageQueue.next(MessageQueue.java:323)
                                                         at android.os.Looper.loop(Looper.java:135)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5490)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
